### ISSUE TITLE
Unknown locations

### ISSUE THREAD

**Issue by nigelhorne** [Humanstate/html-googlemaps-v3#12]
I don't believe this is a problem with the module, but I'm wondering if you can help any way or point me to a place to ask that won't simply reply "the problem is with H:G:V3 not my code".

This code dies:

```
#!/usr/bin/env perl

use HTML::GoogleMaps::V3;

my $place = 'Minster Cemetery, Tothill Street, Minster, Thanet, Kent, England';
my $map = HTML::GoogleMaps::V3->new();
$map->center($place);
$map->add_marker(point => $place) || die "Google maps doesn't know $place";
```

However if I put that location into Google Maps it works fine.
Interestingly if I remove ", Tothill Street" it no longer dies.

**Comment by leejo** [comment]
I suspect the API works slightly differently to the web interface. I suggest looking at the maps API docs and seeing if there's anything we can tweak in the module to "try harder" if no results are found for the initial search.

**Comment by nigelhorne** [comment]
Thanks.  That's what I feared.  Unfortunately this isn't an isolated example.

**Comment by nigelhorne** [comment]
This, however works:

https://maps.googleapis.com/maps/api/geocode/json?address=Minster+Cemetery+Tothill+Street+Minster+Thanet+Kent+England&key=xxxxx

Where xxxxx is, of course, my Key. It even works if I put commas in:

https://maps.googleapis.com/maps/api/geocode/json?address=Minster+Cemetery,+Tothill,+Street,+Minster,+Thanet,+Kent,+England&key=xxxxx

I'm starting to worry if one of my patches has seriously broken your module :-(

**Comment by leejo** [comment]
> I'm starting to worry if one of my patches has seriously broken your module :-(

Hmmm, i doubt that's the case having looked at the various changes. Maybe write a test and git bisect if you suspect there's a problem with a specific commit. I think this may have been a problem in the module from the outset though.

**Comment by nigelhorne** [comment]
OK this is weird. I put in this test case and it doesn't fail and neither does my test program.  However my main program (ged2site) does fail.  Perhaps something is funky there - let me look further.
```
{
		my $place = 'Minster Cemetery, Tothill Street, Minster, Thanet, Kent, England';
		my $map = new_ok('HTML::GoogleMaps::V3');
		ok($map->center($place));
		ok($map->add_marker(point => $place, html => $place));
}
```

**Comment by nigelhorne** [comment]
More funkyness.  The center() and first add_marker() don't fail even though they should:

```
{
	my $place = 'dddddddddddddddddddd';
	my $map = new_ok('HTML::GoogleMaps::V3');
	is($map->center($place), 0, $place);
	is($map->add_marker(point => $place, html => $place), 0, $place);
	$place = 'Minster Cemetery, Tothill Street, Minster, Thanet, Kent, England';
	isnt($map->add_marker(point => $place, html => $place), 0, $place);
}
```

**Comment by nigelhorne** [comment]
I just don't get why entering the URL works, but using Geo::Coder::Google doesn't or why it used to work but no longer does.

**Comment by nigelhorne** [comment]
I've opened RT119288, to see for thoughts from the G:C:G author.

**Comment by nigelhorne** [comment]
Got my answer at http://stackoverflow.com/questions/41209467/google-maps-finds-locations-that-its-api-doesnt

Looks like I'm going to need to rethink.

**Comment by nigelhorne** [comment]
I'm started work on https://github.com/nigelhorne/geo-coder-googleplaces which I should be able to use as a replacement geocoder.  Although thats not documented in the list of options to the constructor, I'm assuming I'll be able to do that.

**Comment by leejo** [comment]
OK, open a PR when you're ready - might be useful to make the (new) dependency optional as part of the constructor to this module and then have it be an optional dependency in the build. Will close this ticket. Thanks!
