### ISSUE TITLE
api_key option - does it do anything?

### ISSUE THREAD

**Issue by nigelhorne** [Humanstate/html-googlemaps-v3#4]
Does the api_option to the constructor work?  I am getting

Google Maps API returned status 'OVER_QUERY_LIMIT' at /home/njh/perl5/perlbrew/perls/perl-5.24.0/lib/site_perl/5.24.0/HTML/GoogleMaps/V3.pm line 94.

 and my Google console says I've done no queries using the key.  Here is my usage:

```
                            my %args;
                            if($opts{'M'}) {
                                    $args{'api_key'} = $opts{'M'};
                            }
                            $map = HTML::GoogleMaps::V3->new(%args);
```

I've added print statements, $opts{'M'} is being set with the key.

**Comment by nigelhorne** [comment]
Here is the exact wording that Google returns, which is why I started wondering if the option does anything:

{
   "error_message" : "You have exceeded your daily request quota for this API. We recommend registering for a key at the Google Developers Console: https://console.developers.google.com/apis/credentials?project=_",
   "results" : [],
   "status" : "OVER_QUERY_LIMIT"
}

**Comment by leejo** [comment]
Yes, it is. I've added a test case as can be seen in the above commit. Please re-open if you find a problem with the module, seems ok to me and to spec.
