### ISSUE TITLE
Scrolling trick

### ISSUE THREAD

**Issue by nigelhorne** [Humanstate/html-googlemaps-v3#6]
I have no idea if this is your problem or mine, but I'm putting this in here in case you can help.  Please take a look at

https://genealogy.nigelhorne.com/cgi-bin/page.fcgi?page=people&entry=I5

Now scroll up until you get the map, then scroll up more and you'll see that the map goes in front of, rather than behind, the banner.  Any ideas?

**Comment by leejo** [comment]
Almost certainly a problem with CSS / page layout and i don't think this is related to the module.

**Comment by nigelhorne** [comment]
The fix is to change this:

```
    my $map = sprintf(
        '<div id="%s" style="width: %s; height: %s"></div>',
        @{$self}{qw/ id width height / },
);
```

to 

```
    my $map = sprintf(
        '<div id="%s" style="width: %s; height: %s; z-index: -1"></div>',
        @{$self}{qw/ id width height / },
);
```

That probably should be configurable.  Would you like a patch?

**Comment by leejo** [comment]
> That probably should be configurable. Would you like a patch?

Yep, create a PR and i'll merge it.
