### ISSUE TITLE
API key Is put in code

### ISSUE THREAD

**Issue by nigelhorne** [Humanstate/html-googlemaps-v3#7]
According to Google

"Do not embed API keys directly in code: API keys that are embedded in code can be accidentally exposed to the public—for example, if you forget to remove the keys from code that you share. Instead of embedding your API keys in your applications, store them in environment variables or in files outside of your application's source tree."

I tend to agree.  I think if the api_key option is given to new() that should be used for the data lookup, but not get embedded in the result from onload_render().

**Comment by leejo** [comment]
I'm going to say "patches welcome" on this one.

**Comment by nigelhorne** [comment]
Before I write the patch, please take a look at the patch I've just submitted to new() - I believe that needs to be added first.

**Comment by leejo** [comment]
#9 has been merged.
