### ISSUE TITLE
api_key not passwd to G:C:G

### ISSUE THREAD

**Issue by nigelhorne** [Humanstate/html-googlemaps-v3#8]
This line in the constructor:

   `geocoder   => Geo::Coder::Google->new,`

doesn't pass api_key to G:C:G.

I suggest something like:

```
sub new {
    my ( $class,%opts ) = @_;

    my $gc;
    if($opts{'api_key'}) {
        $gc = Geo::Coder::Google->new(key => $opts{'api_key'}, apidriver => 3);
   } else {
        $gc = Geo::Coder::Google->new(apidriver => 3);
   }

    return bless( {
        %opts,
        points     => [],
        poly_lines => [],
        geocoder  => $gc,
    }, $class );
}
```

**Comment by leejo** [comment]
Again, I'm going to say "patches welcome" on this one. Thanks!

**Comment by nigelhorne** [comment]
I believe you should be able to use the code I submitted at as a drop-in replacement for "new()".

**Comment by leejo** [comment]
> I believe you should be able to use the code I submitted at as a drop-in replacement for "new()".

Can you submit a pull-request for this?

**Comment by nigelhorne** [comment]
Let me try, I've never done one before so let's give it a go :-)

**Comment by leejo** [comment]
> Let me try, I've never done one before so let's give it a go :-)

Thanks!
